# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2
shared: &shared
  steps:
    - checkout
    - restore_cache:
        key: witan.cic-{{ checksum "deps.edn" }}
    - save_cache:
        paths:
          - ~/.m2
        key: witan.cic-{{ checksum "deps.edn" }}
    - run: clojure -M:test:runner
jobs:
  jdk8:
    docker:
      - image: circleci/clojure:openjdk-8-tools-deps-1.10.1.763
    <<: *shared
  jdk11:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps-1.10.1.763
    <<: *shared
workflows:
  version: 2
  work:
    jobs:
      - jdk8
      - jdk11
